apiVersion: v1
kind: Service
metadata:
  name: service-test
spec: 
  selector:
    project: robo
    component: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
