apiVersion: v1
kind: Pod
metadata: 
  name: test-lb
  labels: 
    
    project: roboshop
    component: frontend
    environment: dev 
    purpose: load-balancer

spec:
  containers:
  - name: nginx
    image: nginx